// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	alert "github.com/Z3Labs/Hackathon/backend/internal/handler/alert"
	apps "github.com/Z3Labs/Hackathon/backend/internal/handler/apps"
	deployments "github.com/Z3Labs/Hackathon/backend/internal/handler/deployments"
	machines "github.com/Z3Labs/Hackathon/backend/internal/handler/machines"
	"github.com/Z3Labs/Hackathon/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 告警处理
				Method:  http.MethodPost,
				Path:    "/v1/alerts",
				Handler: alert.AlertCallBackHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建应用
				Method:  http.MethodPost,
				Path:    "/api/v1/apps",
				Handler: apps.CreateAppHandler(serverCtx),
			},
			{
				// 获取应用列表
				Method:  http.MethodGet,
				Path:    "/api/v1/apps",
				Handler: apps.GetAppListHandler(serverCtx),
			},
			{
				// 更新应用
				Method:  http.MethodPut,
				Path:    "/api/v1/apps/:id",
				Handler: apps.UpdateAppHandler(serverCtx),
			},
			{
				// 获取应用详情
				Method:  http.MethodGet,
				Path:    "/api/v1/apps/:id",
				Handler: apps.GetAppDetailHandler(serverCtx),
			},
			{
				// 获取应用版本列表
				Method:  http.MethodGet,
				Path:    "/api/v1/apps/versions",
				Handler: apps.GetAppVersionsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建发布记录
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments",
				Handler: deployments.CreateDeploymentHandler(serverCtx),
			},
			{
				// 获取发布记录列表
				Method:  http.MethodGet,
				Path:    "/api/v1/deployments",
				Handler: deployments.GetDeploymentListHandler(serverCtx),
			},
			{
				// 更新发布记录
				Method:  http.MethodPut,
				Path:    "/api/v1/deployments/:id",
				Handler: deployments.UpdateDeploymentHandler(serverCtx),
			},
			{
				// 获取发布记录详情
				Method:  http.MethodGet,
				Path:    "/api/v1/deployments/:id",
				Handler: deployments.GetDeploymentDetailHandler(serverCtx),
			},
			{
				// 取消发布
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/cancel",
				Handler: deployments.CancelDeploymentHandler(serverCtx),
			},
			{
				// 取消发布中的设备
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/node-deployments/cancel",
				Handler: deployments.CancelNodeDeploymentHandler(serverCtx),
			},
			{
				// 发布指定设备
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/node-deployments/deploy",
				Handler: deployments.DeployNodeDeploymentHandler(serverCtx),
			},
			{
				// 重试失败的设备
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/node-deployments/retry",
				Handler: deployments.RetryNodeDeploymentHandler(serverCtx),
			},
			{
				// 回滚发布单设备
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/node-deployments/rollback",
				Handler: deployments.RollbackNodeDeploymentHandler(serverCtx),
			},
			{
				// 跳过指定设备
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/node-deployments/skip",
				Handler: deployments.SkipNodeDeploymentHandler(serverCtx),
			},
			{
				// 回滚发布
				Method:  http.MethodPost,
				Path:    "/api/v1/deployments/:id/rollback",
				Handler: deployments.RollbackDeploymentHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建裸金属机器
				Method:  http.MethodPost,
				Path:    "/api/v1/machines",
				Handler: machines.CreateMachineHandler(serverCtx),
			},
			{
				// 获取裸金属机器列表
				Method:  http.MethodGet,
				Path:    "/api/v1/machines",
				Handler: machines.GetMachineListHandler(serverCtx),
			},
			{
				// 更新裸金属机器
				Method:  http.MethodPut,
				Path:    "/api/v1/machines/:id",
				Handler: machines.UpdateMachineHandler(serverCtx),
			},
			{
				// 获取裸金属机器详情
				Method:  http.MethodGet,
				Path:    "/api/v1/machines/:id",
				Handler: machines.GetMachineDetailHandler(serverCtx),
			},
			{
				// 删除裸金属机器
				Method:  http.MethodDelete,
				Path:    "/api/v1/machines/:id",
				Handler: machines.DeleteMachineHandler(serverCtx),
			},
			{
				// 测试机器连接
				Method:  http.MethodPost,
				Path:    "/api/v1/machines/:id/test",
				Handler: machines.TestMachineConnectionHandler(serverCtx),
			},
		},
	)
}
